FROM python:3.9
ENV PYTHONUNBUFFERED 1
RUN mkdir -p /home/app
WORKDIR /home/app
COPY requirements.txt ./requirements.txt
COPY config.local.yaml ./config.local.yaml
RUN pip install -r requirements.txt
COPY . .
RUN apt update && apt install npm -y
RUN npm i -g nodemon
# RUN pip install watchdog
# CMD ["nodemon", "-e", ".py", "--exec", "nameko", "run", "--config", "config.local.yaml", "main"]