FROM python:3.9
ENV PYTHONUNBUFFERED 1
RUN mkdir -p /home/app
WORKDIR /home/app
COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY . .
RUN apt update && apt install npm -y
RUN npm i -g nodemon
# CMD ["nodemon", "-e", ".py", "manage.py", "runserver", "0.0.0.0:3000"]